version: '3.9'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: react_app_prod
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./react-app:/app
